# 这个文件用来测试记录一些常用的python函数
## 2022年6月10日15:34:02：

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [12]:
# python列表
A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print(A)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [23]:
# numpy矩阵
# arrage函数，返回一个ndarray，也就是多维数组
a = np.arange(12)
print('a:\n', a)

# numpy矩阵的reshape方法, 将原数组改变形状
b = a.reshape(3, 4)
print('b = a.reshape(3, 4):\n', b)


a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
b = a.reshape(3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
# 
print('原数组:\n', b)

print('转置数组：')
print('b.T:\n',b.T)
print('b:\n', b)
print('b.transpose():\n', b.transpose())
print('b:\n', b)

原数组:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转置数组：
b.T:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b.transpose():
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
print(b)
# print(pow(b,2))
# print(b[: ,0])
# print(b[:, 0].shape)
# print(pow(b[: ,0],2))
print(b[:,1] * b[:,2])

np.sum(b, 0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2 30 90]


array([12, 15, 18, 21])